//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow.API.Infrastructure.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workflow.API.Infrastructure.DataAccess.Resources.ProjectQueries", typeof(ProjectQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tbl_Project (vcTitle) 
        ///OUTPUT INSERTED.iProjectId 
        ///VALUES (@Title).
        /// </summary>
        internal static string ADD_PROJECT {
            get {
                return ResourceManager.GetString("ADD_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tbl_UserProject (iProjectId, iUserId, bIsOwner) 
        ///VALUES (@ProjectId, @UserId, @IsOwner).
        /// </summary>
        internal static string ADD_PROJECT_USER {
            get {
                return ResourceManager.GetString("ADD_PROJECT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM tbl_UserProject
        ///WHERE iProjectId = @ProjectId AND iUserId = @UserId.
        /// </summary>
        internal static string DELETE_PROJECT_USER {
            get {
                return ResourceManager.GetString("DELETE_PROJECT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	u.iUserId Id,
        ///	u.vcName Name,
        ///	u.vcUsername Username,
        ///	u.vcEmail Email,
        ///	up.bIsOwner IsOwner
        ///FROM tbl_UserProject up
        ///INNER JOIN tbl_User u ON u.iUserId = up.iUserId
        ///WHERE up.iProjectId = @ProjectId.
        /// </summary>
        internal static string GET_ALL_MEMBER_BY_PROJECT_ID {
            get {
                return ResourceManager.GetString("GET_ALL_MEMBER_BY_PROJECT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT 
        ///	p.iProjectId Id, 
        ///	p.vcTitle Title 
        ///FROM tbl_Project p
        ///INNER JOIN tbl_UserProject up ON up.iProjectId = p.iProjectId
        ///WHERE up.iUserId = @UserId ORDER BY p.vcTitle.
        /// </summary>
        internal static string GET_ALL_USER_PROJECTS {
            get {
                return ResourceManager.GetString("GET_ALL_USER_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT 
        ///	p.iProjectId Id, 
        ///	p.vcTitle Title 
        ///FROM tbl_Project p
        ///INNER JOIN tbl_UserProject up ON up.iProjectId = p.iProjectId
        ///WHERE up.iUserId = @UserId ORDER BY p.vcTitle
        ///OFFSET @SkipRows ROWS FETCH NEXT @FetchRows ROWS ONLY.
        /// </summary>
        internal static string GET_ALL_USER_PROJECTS_PAGINATED {
            get {
                return ResourceManager.GetString("GET_ALL_USER_PROJECTS_PAGINATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	p.iProjectId Id, 
        ///	p.vcTitle Title 
        ///FROM tbl_Project p
        ///INNER JOIN tbl_UserProject up ON up.iProjectId = p.iProjectId
        ///WHERE up.iUserId = @UserId and p.iProjectId = @ProjectId.
        /// </summary>
        internal static string GET_BY_USER_ID_PRODUCT_ID {
            get {
                return ResourceManager.GetString("GET_BY_USER_ID_PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	u.iUserId Id,
        ///	u.vcName Name,
        ///	u.vcUsername Username,
        ///	u.vcEmail Email,
        ///	up.bIsOwner IsOwner
        ///FROM tbl_UserProject up
        ///INNER JOIN tbl_User u ON u.iUserId = up.iUserId
        ///WHERE up.iProjectId = @ProjectId AND up.iUserId = @UserId.
        /// </summary>
        internal static string GET_MEMBER_BY_PROJECT_ID_USER_ID {
            get {
                return ResourceManager.GetString("GET_MEMBER_BY_PROJECT_ID_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	COUNT(DISTINCT p.iProjectId) 
        ///FROM tbl_Project p
        ///INNER JOIN tbl_UserProject up ON up.iProjectId = p.iProjectId
        ///WHERE up.iUserId = @UserId.
        /// </summary>
        internal static string GET_USER_PROJECT_COUNT {
            get {
                return ResourceManager.GetString("GET_USER_PROJECT_COUNT", resourceCulture);
            }
        }
    }
}
