//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow.API.Infrastructure.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskItemQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskItemQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workflow.API.Infrastructure.DataAccess.Resources.TaskItemQueries", typeof(TaskItemQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tbl_TaskItem (iProjectId, vcTitle, vcDescription, dtDeadline, iStatus, iCreatorUserId, iAssignedUserId)
        ///OUTPUT
        ///	INSERTED.iTaskId Id
        ///VALUES (@ProjectId, @Title, @Description, @Deadline, @Status, @CreatorUserId, @AssignedUserId).
        /// </summary>
        internal static string ADD_TASK {
            get {
                return ResourceManager.GetString("ADD_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM tbl_TaskItem
        ///OUTPUT
        ///	DELETED.iTaskId Id, 
        ///	DELETED.iProjectId ProjectId, 
        ///	DELETED.vcTitle Title, 
        ///	DELETED.vcDescription Description, 
        ///	DELETED.dtDeadline Deadline, 
        ///	DELETED.iStatus Status, 
        ///	DELETED.iCreatorUserId CreatorUserId, 
        ///	DELETED.iAssignedUserId AssignedUserId
        ///WHERE iTaskId = @TaskId.
        /// </summary>
        internal static string DELETE_TASK {
            get {
                return ResourceManager.GetString("DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	iTaskId Id, 
        ///	iProjectId ProjectId, 
        ///	vcTitle Title, 
        ///	vcDescription Description, 
        ///	dtDeadline Deadline, 
        ///	iStatus Status, 
        ///	iCreatorUserId CreatorUserId, 
        ///	iAssignedUserId AssignedUserId
        ///FROM tbl_TaskItem
        ///WHERE iTaskId = @TaskId.
        /// </summary>
        internal static string GET_BY_ID {
            get {
                return ResourceManager.GetString("GET_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	iTaskId Id, 
        ///	iProjectId ProjectId, 
        ///	vcTitle Title, 
        ///	vcDescription Description, 
        ///	dtDeadline Deadline, 
        ///	iStatus Status, 
        ///	cu.iUserId Id,
        ///	cu.vcName Name,
        ///	cu.vcUsername Username,
        ///	cu.vcEmail Email,
        ///	au.iUserId Id,
        ///	au.vcName Name,
        ///	au.vcUsername Username,
        ///	au.vcEmail Email
        ///FROM tbl_TaskItem ti
        ///LEFT JOIN tbl_User cu ON cu.iUserId = ti.iCreatorUserId
        ///LEFT JOIN tbl_User au ON au.iUserId = ti.iAssignedUserId
        ///WHERE iProjectId = @ProjectId AND (@IncludeArchivedTask = 1 OR  ti.iStatus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_WITH_TASK_BY_PROJECT_ID {
            get {
                return ResourceManager.GetString("GET_WITH_TASK_BY_PROJECT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE tbl_TaskItem SET
        ///	iProjectId = @ProjectId,
        ///	vcTitle = @Title,
        ///	vcDescription = @Description,
        ///	dtDeadline = @Deadline,
        ///	iStatus = @Status,
        ///	iCreatorUserId = @CreatorUserId,
        ///	iAssignedUserId =  @AssignedUserId
        ///OUTPUT
        ///	INSERTED.iTaskId Id, 
        ///	INSERTED.iProjectId ProjectId, 
        ///	INSERTED.vcTitle Title, 
        ///	INSERTED.vcDescription Description, 
        ///	INSERTED.dtDeadline Deadline, 
        ///	INSERTED.iStatus Status, 
        ///	INSERTED.iCreatorUserId CreatorUserId, 
        ///	INSERTED.iAssignedUserId AssignedUserId
        ///WHERE iTaskI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UPDATE_TASK {
            get {
                return ResourceManager.GetString("UPDATE_TASK", resourceCulture);
            }
        }
    }
}
