//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workflow.API.Infrastructure.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TokenQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workflow.API.Infrastructure.DataAccess.Resources.TokenQueries", typeof(TokenQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE tbl_Token AS Target
        ///USING (SELECT  
        ///	@UserId iUserId, 
        ///	@TokenType iTokenType,
        ///	@TokenString vcTokenString,
        ///	@CreationDateTime dtCreationDateTime,
        ///	@ExpiryDateTime dtExpiryDateTime)
        ///	AS Source
        ///ON Source.iUserId = Target.iUserId AND Source.iTokenType = Target.iTokenType
        ///WHEN NOT MATCHED BY Target THEN
        ///	INSERT (iUserId, iTokenType, vcTokenString, dtCreationDateTime, dtExpiryDateTime)
        ///	VALUES (Source.iUserId, Source.iTokenType, Source.vcTokenString, Source.dtCreationDateTime, Source.dtExpiryDa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ADD_OR_UPDATE_TOKEN {
            get {
                return ResourceManager.GetString("ADD_OR_UPDATE_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM tbl_Token
        ///OUTPUT
        ///	DELETED.iTokenId Id,
        ///	DELETED.iUserId UserId,
        ///	DELETED.iTokenType TokenType,
        ///	DELETED.vcTokenString TokenString,
        ///	DELETED.dtCreationDateTime CreationDateTime,
        ///	DELETED.dtExpiryDateTime ExpiryDateTime
        ///WHERE iTokenId = @TokenId.
        /// </summary>
        internal static string DELETE_TOKEN {
            get {
                return ResourceManager.GetString("DELETE_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	iTokenId Id,
        ///	iUserId UserId,
        ///	iTokenType TokenType,
        ///	vcTokenString TokenString,
        ///	dtCreationDateTime CreationDateTime,
        ///	dtExpiryDateTime ExpiryDateTime
        ///FROM tbl_Token
        ///WHERE vcTokenString = @TokenStr AND iTokenType = @TokenType.
        /// </summary>
        internal static string GET_BY_TOKEN_STR_TOKEN_TYPE {
            get {
                return ResourceManager.GetString("GET_BY_TOKEN_STR_TOKEN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	iTokenId Id,
        ///	iUserId UserId,
        ///	iTokenType TokenType,
        ///	vcTokenString TokenString,
        ///	dtCreationDateTime CreationDateTime,
        ///	dtExpiryDateTime ExpiryDateTime
        ///FROM tbl_Token
        ///WHERE iUserId = @UserId AND iTokenType = @TokenType.
        /// </summary>
        internal static string GET_BY_USER_ID_TOKEN_TYPE {
            get {
                return ResourceManager.GetString("GET_BY_USER_ID_TOKEN_TYPE", resourceCulture);
            }
        }
    }
}
